# /home/bruno/lightmanager/scripts/logrotate.conf
# Configuração de rotação local de logs para o Light Manager

/home/bruno/lightmanager/logs/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
